#注意所有的冒号后边都有个空格 别删别删



#多看阅读 cookie为app里的全部cookie
duokan:
  cookie: 
  
#wps 小程序个人中心账号id 一串数字
wps:
  uid: 123456
  
#橙光游戏app随便抓个包就有token
cg:
  token: 
  skey: 
  
#绅士领域个人uid可抓签到包看到
ssly:
  uid: 12487
  
#时光相册 手机号密码 请抓登陆包查看 手机号里包括区号 86啥的 密码为加密后的密码
everphoto:
  phone: 8611012451110
  password: 

#书香门第 登陆账号密码(只支持字母+数字组合账号)
sxmd:
  account: 
  password: 
  
#uclub这个签到失效了 在cookie里
ucloud:
  token: 
  
#人人视频app安卓端 在headers里
rrsp:
  rrtoken: rrtv-12345678910jqka

#好游快爆 去我的-赚爆米花-任务里 随便抓一个post包 请求数据里有scookie 直接分享商品链接查看  gid 和 key 分享需要兑换的商品链接查看 例https://huodong3.3839.com/n/hykb/bmhstore2/inc/libao/index.php?gid=6237 比如上面这个 gid就是6237  key就是 libao 就是查看inc/后面的那个东西

hykb:
  scookie:  
  gid: 
  key: 

#网易蜗牛读书  都在cookie或者headers里 抓签到包最方便
du163:
  xsrf: 
  X-Auth-Token: 

#吾爱破解 全部cookie
w2pj:
  cookie:
  
# 香网小说网页端 全部cookie
xiang5:
  cookie:  
  
#京东 全部cookie
jd:
  cookie: 

#晋江小说 手机版网页端 m.jjwxc.net cookie中sid 最好抓签到的 填完整 sid=xxx
jjwxc:
  cookie: sid=20070297_1234576798787

#什么值得买网页端 全部cookie
smzdm:
  cookie: __ckguid=FA83Q2fLqlYi1yVQ4BgtC96; __jsluid_s=edb681e64d9f804ab5d58c1edbd9fdd0; r_sort_type=score; _zdmA.vid=*; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221771f0eb01d7fa-0ae0bc6cc76fc9-c791039-1296000-1771f0eb01e5f8%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E8%87%AA%E7%84%B6%E6%90%9C%E7%B4%A2%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC%22%2C%22%24latest_referrer%22%3A%22https%3A%2F%2Fwww.google.com.hk%2F%22%2C%22%24latest_landing_page%22%3A%22https%3A%2F%2Fwww.smzdm.com%2F%22%7D%2C%22%24device_id%22%3A%221771f0eb01d7fa-0ae0bc6cc76fc9-c791039-1296000-1771f0eb01e5f8%22%7D; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1617781657; zdm_qd=%7B%22referrer%22%3A%22https%3A%2F%2Fwww.google.com.hk%2F%22%7D; _ga=GA1.2.1816950551.1617781659; _gid=GA1.2.1856542250.1617781659; footer_floating_layer=0; ad_date=7; ad_json_feed=%7B%7D; user=user%3A6685292192%7C6685292192; smzdm_id=6685292192; device_id=32650288541617781719197684a8193e762a8e1b87a2f9310ca338b647; sess=OTRhMjh8MTYyMjk2NTcxOXw2Njg1MjkyMTkyfGJiMmEzODgxMzdkMDhmNGMwZmUyM2FlZjkyNzAwNTY1fDMyNjUwMjg4NTQxNjE3NzgxNzE5MTk3Njg0YTgxOTNlNzYyYThlMWI4N2EyZjkzMTBjYTMzOGI2NDd8d2Vi; userId=user:6685292192|6685292192; __gads=ID=4abbdfc63050353f:T=1617781668:S=ALNI_MYlLaSjiNUdlHuBoBrEIt-i33KGpQ; homepage_sug=c; _zdmA.uid=ZDMA.ZsetJq6RM.1617781843.2419200; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1617781843; bannerCounter=%5B%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A2%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A2%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%5D; amvid=52979331a1febf50cec36a852eaa0060; _zdmA.time=1617782009688.0.https%3A%2F%2Fwww.smzdm.com%2F 
  
#网易云游戏网页端  请求头里
cg163:
  Authorization:  

#龙空论坛 全部cookie
lkong:
  cookie: 
  
#经管之家 全部cookie
pinggu:
  cookie:  
  
#nga论坛 app端 
nga:
  uid: 
  accesstoken: 

#cdsn 网页 全部cookie
csdn:
  cookie:  
  
#mt论坛 全部cookie
mt:
  cookie:  
  time: ''

#sf轻小说 app
sfacg:
  cookie: 

#猫耳fm 网页 全部cookie
maoer:
  cookie:  
  
  
#爱好论坛 全部cookie
aihao:
  cookie:  
  
#刺猬猫小说 账号密码
hbooker:
  login_name: 
  passwd: 

#ACFun 手机号 密码
acfun:
  phone: 
  password: 

#传奇gm论坛 全部cookie
diygm:
  cookie:  
  
#一亩三分地 登陆账号 密码 (不要设置登录问题) 联众打码平台 账号密码
ym3fd:
  username: 
  password: 
  lzusername: 
  lzpassword: 

#次元狗 全部cookie
acdog:
  cookie:  
  
#登陆联想智选app的手机号密码以及请求头header中的baseinfo
lenovo:
  account: 
  password: 
  baseinfo: 
  
#数码之家全部cookie
mydigit:
  cookie: cc405_oltoken=init; safedog-flow-item=; Hm_lvt_ab859ea8b00af2b447b0a7cdc5e2e13d=1617865254; Hm_lpvt_ab859ea8b00af2b447b0a7cdc5e2e13d=1617865254; cc405_cloudClientUid=98102991; cc405_winduser=UAMEAwsBDW8EDlcDBwNQBgAAVwEBCQEACgIAUlVVVwAGBlVSAAcJCTs; cc405_ck_info=%2F%09; cc405_online_info=1617871447%09119%09622; cc405_lastpos=index; cc405_lastvisit=35%091617871482%09%2Findex.php; cc405_ci=index%091617871482%09%09
#联动云租车 全部cookie
ldygo:
  cookie: 
  
#玩物志好物商店 如果是小程序登陆的 type 默认为wx 如果是网页的就随便改比如 web 123等等,只要不是wx就行,小程序可不填cookie,网页需要
coolbuy:
  type: wx
  authorization: 
  xcsrftoken: 
  cookie:   
  
#阅次元论坛:
abooky:
  cookie: 
  
#富贵论坛
fglt: 
  cookie: 
 
#纪录片之家
jlpzj: 
  cookie: 
  
#ug爱好者
ugsnx:
  cookie:  
  
#好书友论坛 
hsy: 
  cookie: 
  
#togamemod
togamemod: 
  cookie: 
  
  
  
