name: 签到盒

on:
    workflow_dispatch:
    schedule:
        - cron: "0 8 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【中国电信签到】"
              run: node scripts/smzdm.js
              env:
                SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
                QMSGAPI: ${{ secrets.QMSGAPI }}
                sckey: ${{ secrets.sckey }}
                tgapi: ${{ secrets.tgapi }}
